#!/usr/bin/env julia

using ArgParse, OSMPBF

s = ArgParseSettings()

@add_arg_table! s begin
    "--filter-ways"
        help = "Filter ways based on tags"
        arg_type = String
    "--filter-nodes"
        help = "Filter nodes based on tags"
        arg_type = String
    "--no-relations"
        help = "Don't parse relations"
    "--write-gdal-ways"
        help = "Write ways to a GDAL file"
        arg_type = String
    "--write-gdal-nodes"
        help = "Write nodes to a GDAL file"
        arg_type = String
    "--gdal-driver"
        help = "GDAL driver to use (default 'ESRI Shapefile')"
        default = "ESRI Shapefile"
    "--gdal-tags"
        help = "Tags to retain in GDAL output, comma-separated"
        arg_type = String
        default = "highway,name"
    "input_file"
        help = "Input file, OSM PBF format"
end

OSMPBF.OSMTool.main(parse_args(s))